services:
  - type: web
    name: pikngo-user-service
    env: docker
    rootDir: user-service
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://ep-calm-bird-apehu4fz-pooler.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_7oM9ELuxjhUb
      - key: MAIL_USERNAME
        value: welcomedevil006@gmail.com
      - key: MAIL_PASSWORD
        sync: false # Set this manually in Render dashboard
