services:
  - type: web
    name: pikngo-user-service
    plan: free
    env: docker
    rootDir: user-service
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_CONFIG
        sync: false
      - key: MAPBOX_TOKEN
        sync: false
      - key: PORT
        value: 8080
